name: chords_khmer_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">= 2.12.0"


dependencies:
  flutter:
    sdk: flutter 

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.1.0


  js: ^0.6.2
  http: ^0.13.5
  file_picker: ^5.2.7
  connectivity_plus: ^3.0.4
  firebase_messaging: ^14.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
      
  flutter_native_splash: ^2.2.19
         
  flutter_lints: ^2.0.0


  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/playstore.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
      - lib/assets/images/sample_chords.png
      - lib/assets/images/metallica.jpg
      - lib/assets/images/music.png
      - lib/assets/images/profile.png
      - lib/assets/images/slipknot.jpg
      - lib/assets/images/tifong.jpg
      - lib/assets/images/ac_dc.jpg
      - lib/assets/images/playstore.png
      - lang/en.json
      - lang/kh.json

